network: mainnet
urls:
  api: 'https://api.multiversx.com'
  gateway: 'https://gateway.multiversx.com'
  elastic: 'https://index.multiversx.com'
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
flags:
  useKeepAliveAgent: true
testConfig:
  acceptablePercentageDifference: 10
  apiSleepTime: 10000
  batchApiRequestSize: 10
