network: devnet
urls:
  api: 'https://devnet-api.multiversx.com'
  gateway: 'https://devnet-gateway.multiversx.com'
  elastic: 'https://devnet-index.multiversx.com'
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
flags:
  useKeepAliveAgent: true
testConfig:
  acceptablePercentageDifference: 10
  apiSleepTime: 10000
  batchApiRequestSize: 10
